[package]
name = "nota-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23.1"
chrono = "0.4.45"
dirs = "6.0.0"
futures-util = "0.3.33"
glob = "0.3.4"
rand = "0.10.2"
reqwest = { version = "0.13.4", features = ["json"] }
sea-orm = { version = "2.0.2", features = ["sqlx-sqlite", "runtime-tokio"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.30.0", features = [
    "rustls-tls-native-roots",
] }

[dev-dependencies]
tempfile = "3.27.0"
